# Generated by Django 3.1.4 on 2021-09-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210917_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/profile_default.png', null=True, upload_to='profiles/'),
        ),
    ]
