# Generated by Django 3.1.4 on 2021-09-27 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210926_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-total_votes', 'title']},
        ),
    ]
